version: "3.7"

services:
  nginx:
    build: name_server/nginx
    image: kirillfedoseev/p2_nginx:v1
    ports:
      - target: 8000
        published: 8000
        mode: host
    volumes:
      - sockets:/tmp/sockets
    deploy:
      placement:
        constraints:
          - node.labels.primary==true

  django:
    build: name_server/django
    image: kirillfedoseev/p2_name_server:v1
    volumes:
      - sockets:/tmp/sockets
    environment:
      MODE: "dev"
      DJANGO_DEBUG: "True"
      DJANGO_APP_NAME: "name_server"
      DJANGO_SECRET_KEY: "aaaaaaaaaaaaaaaaaaaaaa"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_LOGGING_LEVEL: "INFO"
      DJANGO_DATABASE_NAME: "pgdb"
      DJANGO_DATABASE_USER: "pguser"
      DJANGO_DATABASE_PASSWORD: "pgpassword"
      DJANGO_DATABASE_HOST: "postgres"
      DJANGO_DATABASE_PORT: "5432"
      NUM_OF_REPLICAS: "2"
      STORAGE_SERVER_PORT: "5000"
      UWSGI_PROCESSES: "2"
      UWSGI_THREADS: "2"
      UWSGI_HARAKIRI: "60"
      UWSGI_MAX_REQUESTS: "100"
    deploy:
      placement:
        constraints:
          - node.labels.primary==true

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    deploy:
      placement:
        constraints:
          - node.labels.primary==true

  storage:
    build: storage_server
    image: kirillfedoseev/p2_storage_server:v1
    volumes:
      - /save_folder:/save_folder
    environment:
      NAME_SERVER_IP: nginx
      NAME_SERVER_PORT: 8000
      STORAGE_SERVER_PORT: 5000
    ports:
      - target: 5000
        published: 5000
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.primary!=true

volumes:
  postgres-data:
  sockets:

