version: "3.7"

x-django-common-volumes: &django-common-volumes
  - "sockets:/tmp/sockets"
  - "./django:/app"

x-django-common-environment: &django-common-environment
  MODE: "dev"
  DJANGO_DEBUG: "True"
  DJANGO_APP_NAME: "name_server"
  DJANGO_SECRET_KEY: "aaaaaaaaaaaaaaaaaaaaaa"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGGING_LEVEL: "INFO"
  DJANGO_DATABASE_NAME: "pgdb"
  DJANGO_DATABASE_USER: "pguser"
  DJANGO_DATABASE_PASSWORD: "pgpassword"
  DJANGO_DATABASE_HOST: "postgres"
  DJANGO_DATABASE_PORT: "5432"
  NUM_OF_REPLICAS: "2"
  STORAGE_SERVER_PORT: "5000"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: "yuloskov/nginx_reverse_proxy:latest"
    ports:
      - "8000:8000"
    volumes:
      - "sockets:/tmp/sockets"
    networks:
      name_server_default:
        aliases:
          - nginx
      deploy:
        mode: replicated
        replicas: 1
    restart: "always"

  django:
    build: django
    image: "yuloskov/name_server:latest"
    volumes: *django-common-volumes
    environment:
      <<: *django-common-environment
      UWSGI_PROCESSES: "2"
      UWSGI_THREADS: "2"
      UWSGI_HARAKIRI: "60"
      UWSGI_MAX_REQUESTS: "100"
      STORAGE_SERVER_PORT: "5000"
    depends_on:
      - postgres
    networks:
      name_server_default:
        aliases:
          - django
      deploy:
        mode: replicated
        replicas: 1
    restart: "always"

  postgres:
    image: "postgres:12"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_DB=pgdb"
      - "POSTGRES_USER=pguser"
      - "POSTGRES_PASSWORD=pgpassword"
    networks:
      name_server_default:
        aliases:
          - postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.postgres==true"
    restart: "always"

  storage:
    image: "yuloskov/storage_server:latest"
    volumes:
      - "/save_folder:/save_folder"
    environment:
      - "NAME_SERVER_IP=nginx"
      - "NAME_SERVER_PORT=8000"
      - "STORAGE_SERVER_PORT=5000"
    networks:
      name_server_default:
        aliases:
          - storage
    deploy:
      mode: replicated
      replicas: 3
    restart: "always"

volumes:
  django-static:
  django-media:
  postgres-data:
  rabbitmq-data:
  sockets:

