# Generated by Django 3.0.10 on 2020-10-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='storage',
            field=models.ManyToManyField(related_name='files', to='name_server.Storage'),
        ),
    ]
