version: "3.7"

x-django-common-volumes: &django-common-volumes
  - "sockets:/tmp/sockets"
  - "./django:/app"

x-django-common-environment: &django-common-environment
  MODE: "dev"
  DJANGO_DEBUG: "True"
  DJANGO_APP_NAME: "name_server"
  DJANGO_SECRET_KEY: "aaaaaaaaaaaaaaaaaaaaaa"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGGING_LEVEL: "INFO"
  DJANGO_DATABASE_NAME: "pgdb"
  DJANGO_DATABASE_USER: "pguser"
  DJANGO_DATABASE_PASSWORD: "pgpassword"
  DJANGO_DATABASE_HOST: "postgres"
  DJANGO_DATABASE_PORT: "5432"
  NUM_OF_REPLICAS: "2"
  STORAGE_SERVER_PORT: "5000"

services:
  nginx:
    build: nginx
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - "sockets:/tmp/sockets"
    restart: "always"

  django:
    build: django
    image: "dss/django"
    volumes: *django-common-volumes
    environment:
      <<: *django-common-environment
      UWSGI_PROCESSES: "2"
      UWSGI_THREADS: "2"
      UWSGI_HARAKIRI: "60"
      UWSGI_MAX_REQUESTS: "100"
      STORAGE_SERVER_PORT: "5000"
    depends_on:
      - postgres
    restart: "always"

  postgres:
    image: "postgres:12"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_DB=pgdb"
      - "POSTGRES_USER=pguser"
      - "POSTGRES_PASSWORD=pgpassword"
    restart: "always"

volumes:
  django-static:
  django-media:
  postgres-data:
  rabbitmq-data:
  sockets:

