# Generated by Django 3.0.10 on 2020-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UP', 'Server is up'), ('DN', 'Server is down'), ('PD', 'Server is doing some task')], default='UP', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('storage', models.ManyToManyField(to='main.Storage')),
            ],
        ),
    ]
