# Generated by Django 3.0.10 on 2020-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('UP', 'Server is up'), ('DN', 'Server is down'), ('PD', 'Server is doing some task')], default='UP', max_length=2),
        ),
    ]
